package ast.E;

public enum TipoE {
  SUMA, RESTA, MUL, DIV, ELEV, NUM, OR, AND, EQUAL, NOT, GREATERTHAN, LESSTHAN,
  GREATEREQUAL, LESSEQUAL, NOTEQUAL, SQUAREBRACKET, BASICTRUE, BASICFALSE, IDEN, MENOS, FUNCION, DOT, ASTERISK,EPOINTER
}
