
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Jun 15 21:58:10 CEST 2020
//----------------------------------------------------

package asint;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int CONST = 35;
  public static final int POR = 8;
  public static final int ELEV = 27;
  public static final int GE = 17;
  public static final int SL = 24;
  public static final int CASE = 41;
  public static final int PC = 23;
  public static final int PA = 22;
  public static final int INT = 29;
  public static final int NOT = 13;
  public static final int AND = 11;
  public static final int IGUAL = 2;
  public static final int LT = 14;
  public static final int OR = 12;
  public static final int DIV = 9;
  public static final int CC = 21;
  public static final int IF = 25;
  public static final int CA = 20;
  public static final int LE = 16;
  public static final int BOOLEAN = 39;
  public static final int EOF = 0;
  public static final int LC = 19;
  public static final int RETURN = 38;
  public static final int LA = 18;
  public static final int EQUAL = 28;
  public static final int TRUE = 31;
  public static final int NEW = 43;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MENOS = 7;
  public static final int MOD = 10;
  public static final int PUNTERO = 44;
  public static final int SWITCH = 37;
  public static final int PCOMA = 4;
  public static final int ENT = 46;
  public static final int ELSE = 33;
  public static final int PUNTO = 5;
  public static final int IDEN = 45;
  public static final int WHILE = 36;
  public static final int DEFAULT = 40;
  public static final int THEN = 30;
  public static final int PROC = 34;
  public static final int FALSE = 32;
  public static final int STRUCT = 42;
  public static final int GT = 15;
  public static final int DO = 26;
  public static final int MAS = 6;
}

